{-# LANGUAGE OverloadedStrings #-}

-- | Developer tool that emits SQL migration files for the dbsync schema.
--
-- @baseline@ writes the frozen v1 schema anchor; @generate@ renders a draft
-- migration from the typed schema diff. This tool never touches a database —
-- the boot-time runner applies the committed files.
module Main (main) where

import Cardano.Prelude

import qualified Data.Text as T
import qualified Data.Text.IO as TIO

import Options.Applicative

import System.Directory (createDirectoryIfMissing)
import System.FilePath ((</>))

import DbSync.Db.Schema.Init (initSchemaStatements)
import DbSync.Db.Schema.Migration.Diff (schemaDiff)
import DbSync.Db.Schema.Migration.Render (renderChange)
import DbSync.Extractor (ExtractorDef (..))
import DbSync.Extractor.Registry (allDeclaredTables, allKnownExtractors)
import DbSync.Schema.Version (currentSchemaVersion)

-- ---------------------------------------------------------------------------
-- * CLI
-- ---------------------------------------------------------------------------

data Command
  = Baseline FilePath
  | Generate FilePath

defaultOutDir :: FilePath
defaultOutDir = "dbsync-db" </> "migrations"

main :: IO ()
main = do
  cmd <- execParser opts
  case cmd of
    Baseline dir -> writeBaseline dir
    Generate dir -> writeGenerated dir
  where
    opts =
      info
        (commandParser <**> helper)
        (fullDesc <> progDesc "Generate dbsync schema migration files.")

commandParser :: Parser Command
commandParser =
  hsubparser
    ( command
        "baseline"
        ( info
            (Baseline <$> outDirParser)
            (progDesc "Write the frozen v1 baseline anchor (0001-baseline-v1.sql).")
        )
        <> command
          "generate"
          ( info
              (Generate <$> outDirParser)
              (progDesc "Render a draft migration from the typed schema diff.")
          )
    )

outDirParser :: Parser FilePath
outDirParser =
  strOption
    ( long "out-dir"
        <> metavar "DIR"
        <> value defaultOutDir
        <> showDefault
        <> help "Directory to write migration files into."
    )

-- ---------------------------------------------------------------------------
-- * baseline
-- ---------------------------------------------------------------------------

writeBaseline :: FilePath -> IO ()
writeBaseline dir = do
  createDirectoryIfMissing True dir
  let path = dir </> "0001-baseline-v1.sql"
  TIO.writeFile path baselineSql
  TIO.putStrLn ("Wrote " <> T.pack path)

-- | The baseline reuses 'initSchemaStatements' over every known extractor's
-- tables, so it is byte-for-byte the DDL a fresh 'initSchema' would run.
baselineSql :: Text
baselineSql =
  baselineHeader
    <> T.intercalate "\n" (initSchemaStatements (concatMap pdTables allKnownExtractors))

baselineHeader :: Text
baselineHeader =
  T.unlines
    [ "-- dbsync schema baseline (schema version 1)."
    , "-- Generated by gen-migration; do not edit by hand."
    , "--"
    , "-- Frozen record of the v1 logical schema: this file plus the incremental"
    , "-- vN migration files rebuild the schema from empty. A fresh production"
    , "-- database is built by initSchema, not by this file."
    , ""
    ]

-- ---------------------------------------------------------------------------
-- * generate
-- ---------------------------------------------------------------------------

writeGenerated :: FilePath -> IO ()
writeGenerated dir
  | currentSchemaVersion < 2 =
      TIO.putStrLn
        ( "Nothing to generate at schema version "
            <> T.pack (show currentSchemaVersion)
            <> ": v1 is the frozen baseline (0001-baseline-v1.sql). Bump "
            <> "currentSchemaVersion before drafting a migration."
        )
  | otherwise = do
      createDirectoryIfMissing True dir
      let path = dir </> generatedFileName currentSchemaVersion
      TIO.writeFile path generatedSql
      TIO.putStrLn ("Wrote " <> T.pack path)

generatedFileName :: Int -> FilePath
generatedFileName v =
  T.unpack (T.justifyRight 4 '0' n <> "-v" <> n <> ".sql")
  where
    n = T.pack (show v)

generatedSql :: Text
generatedSql =
  generatedHeader
    <> T.unlines (map renderChange (schemaDiff [] allDeclaredTables))

generatedHeader :: Text
generatedHeader =
  T.unlines
    [ "-- dbsync schema migration draft (schema version " <> T.pack (show currentSchemaVersion) <> ")."
    , "-- Generated by gen-migration; review and complete before committing."
    , "--"
    , "-- The diff is taken against an EMPTY prior schema, so this renders the"
    , "-- full CREATE set rather than incremental ALTERs against the previous"
    , "-- schema version."
    , "--"
    , "-- Hand-written data-semantic steps (renames, backfills, recomputes) go"
    , "-- below the generated DDL."
    , ""
    ]
