#!/usr/bin/env bash
# Regenerates scripts/iog-lib-pins.env from cardano-node's flake.lock.
#
# The cardano-node tag is read from cabal.project's source-repository-package
# stanza — the single source of truth for the node pairing. The flake.lock at
# that tag names the exact libsodium / secp256k1 / blst revisions cardano-node
# itself is built against; we vendor them so release builds link the same
# versions. No nix involved: the lock file is plain JSON.
#
# Usage:
#   scripts/release/update-iog-lib-pins.sh          rewrite iog-lib-pins.env
#   scripts/release/update-iog-lib-pins.sh --check  fail if the vendored file is stale
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/../.." && pwd)
pins_file=$repo_root/scripts/release/iog-lib-pins.env

command -v jq >/dev/null || { echo "error: jq is required" >&2; exit 1; }

node_tag=$(awk '
  /location:.*IntersectMBO\/cardano-node$/ { found = 1; next }
  found && /tag:/ { print $2; exit }
' "$repo_root/cabal.project")
[ -n "$node_tag" ] || {
  echo "error: cardano-node tag not found in cabal.project" >&2
  exit 1
}

lock_url="https://raw.githubusercontent.com/IntersectMBO/cardano-node/${node_tag}/flake.lock"
lock=$(curl -sfL "$lock_url") || {
  echo "error: failed to fetch $lock_url" >&2
  exit 1
}

# Reads owner/repo and rev of a flake.lock input node. Fails loudly if the
# node vanished (upstream restructured its flake) rather than emitting an
# empty pin.
pin() {
  jq -er --arg n "$1" --arg f "$2" '.nodes[$n].locked[$f]' <<<"$lock" || {
    echo "error: node '$1' missing from $lock_url — upstream flake restructured?" >&2
    exit 1
  }
}

generated=$(
  cat <<EOF
# Generated by scripts/release/update-iog-lib-pins.sh — do not edit by hand.
# IOG C library revisions from IntersectMBO/cardano-node's flake.lock at the
# tag cabal.project pins. Consumed by scripts/release/build-iog-libs.sh.
NODE_TAG=$node_tag
SODIUM_REPO=$(pin sodium owner)/$(pin sodium repo)
SODIUM_REV=$(pin sodium rev)
SECP256K1_REPO=$(pin secp256k1 owner)/$(pin secp256k1 repo)
SECP256K1_REV=$(pin secp256k1 rev)
BLST_REPO=$(pin blst owner)/$(pin blst repo)
BLST_REV=$(pin blst rev)
EOF
)

if [ "${1:-}" = "--check" ]; then
  if diff -u "$pins_file" <(printf '%s\n' "$generated"); then
    echo "iog-lib-pins.env is up to date (cardano-node $node_tag)"
  else
    echo "error: scripts/release/iog-lib-pins.env is stale for cardano-node $node_tag." >&2
    echo "Run scripts/release/update-iog-lib-pins.sh and commit the result." >&2
    exit 1
  fi
else
  printf '%s\n' "$generated" >"$pins_file"
  echo "wrote $pins_file (cardano-node $node_tag)"
fi
