{-# LANGUAGE OverloadedStrings #-}

-- | Pre-allocate every assignable id a block needs in one libpq
-- pipeline round-trip, and stash the results in per-table queues the
-- Follow 'IdResolver' pops without a round-trip.
--
-- Only FK-referenced tables need this. A leaf table uses
-- @GENERATED BY DEFAULT AS IDENTITY@ and lets PostgreSQL allocate at
-- INSERT time.
module DbSync.Phase.Following.IdAllocator
  ( PreAllocatedIds (..)
  , allocateAllIds
  , popHead
  , unused
  ) where

import Cardano.Prelude

import Data.IORef (IORef, atomicModifyIORef', newIORef, readIORef)
import qualified Hasql.Connection as Conn
import qualified Hasql.Pipeline as Pipeline
import qualified Hasql.Session as Sess

import DbSync.Db.Run (useConn)
import DbSync.Db.Schema.Ids
  ( CollateralTxOutId (..)
  , CommitteeId (..)
  , ConstitutionId (..)
  , GovActionProposalId (..)
  , ParamProposalId (..)
  , PoolMetadataRefId (..)
  , PoolUpdateId (..)
  , RedeemerId (..)
  , TxId (..)
  , TxOutId (..)
  )
import DbSync.Db.Schema.Governance
  ( committeeTableDef
  , constitutionTableDef
  , govActionProposalTableDef
  , paramProposalTableDef
  )
import DbSync.Db.Schema.ScriptsDatums (redeemerTableDef)
import DbSync.Db.Schema.Types (TableDef)
import DbSync.Db.Statement.IdAllocator (bulkNextvalStmt)
import DbSync.Db.Schema.UTxO (collateralTxOutTableDef, txOutTableDef)
import DbSync.Db.Schema.Core (txTableDef)
import DbSync.Db.Schema.Pool (poolMetadataRefTableDef, poolUpdateTableDef)
import DbSync.Phase.Following.IdCounts (IdCounts (..))

-- | Per-sequence FIFO of ids allocated for the current block. One
-- 'IORef' per sequence lets the resolver pop without contending
-- across tables. 'allocateAllIds' fills each queue once and the
-- extractor pass drains it once.
data PreAllocatedIds = PreAllocatedIds
  { paiTxIds                :: !(IORef [TxId])
  , paiTxOutIds             :: !(IORef [TxOutId])
  , paiCollateralTxOutIds   :: !(IORef [CollateralTxOutId])
  , paiPoolUpdateIds        :: !(IORef [PoolUpdateId])
  , paiPoolMetadataRefIds   :: !(IORef [PoolMetadataRefId])
  , paiRedeemerIds          :: !(IORef [RedeemerId])
  , paiGovActionProposalIds :: !(IORef [GovActionProposalId])
  , paiParamProposalIds     :: !(IORef [ParamProposalId])
  , paiCommitteeIds         :: !(IORef [CommitteeId])
  , paiConstitutionIds      :: !(IORef [ConstitutionId])
  }

-- | Panics when the extractor pass requests more ids than
-- 'allocateAllIds' pre-fetched. That means 'IdCounts' undercounted,
-- and the test suite must catch it loudly.
popHead :: Text -> IORef [a] -> IO a
popHead label ref =
  atomicModifyIORef' ref $ \case
    (x : xs) -> (xs, x)
    []       -> panic $
      "IdAllocator.popHead: queue exhausted for " <> label
        <> ". IdCounts undercount; investigate the count walker."

-- | Ids left in a queue. Tests assert the extractor consumed exactly
-- what the allocator pre-fetched.
unused :: IORef [a] -> IO Int
unused ref = length <$> readIORef ref

-- | Allocate every ID the block will need in one pipeline batch.
allocateAllIds :: Conn.Connection -> IdCounts -> IO PreAllocatedIds
allocateAllIds conn counts = do
  let pipeline =
        AllocatedIdsRaw
          <$> allocFor txTableDef                (icTxIds counts)                TxId
          <*> allocFor txOutTableDef             (icTxOutIds counts)             TxOutId
          <*> allocFor collateralTxOutTableDef   (icCollateralTxOutIds counts)   CollateralTxOutId
          <*> allocFor poolUpdateTableDef        (icPoolUpdateIds counts)        PoolUpdateId
          <*> allocFor poolMetadataRefTableDef   (icPoolMetadataRefIds counts)   PoolMetadataRefId
          <*> allocFor redeemerTableDef          (icRedeemerIds counts)          RedeemerId
          <*> allocFor govActionProposalTableDef (icGovActionProposalIds counts) GovActionProposalId
          <*> allocFor paramProposalTableDef     (icParamProposalIds counts)     ParamProposalId
          <*> allocFor committeeTableDef         (icCommitteeIds counts)         CommitteeId
          <*> allocFor constitutionTableDef      (icConstitutionIds counts)      ConstitutionId

  raw <- useConn "Phase.Following.IdAllocator" conn (Sess.pipeline pipeline)
  wrapInRefs raw

-- | Raw lists as the pipeline returns them. 'wrapInRefs' converts
-- them to the queue shape the extractor pops from.
data AllocatedIdsRaw = AllocatedIdsRaw
  { rTxIds                :: ![TxId]
  , rTxOutIds             :: ![TxOutId]
  , rCollateralTxOutIds   :: ![CollateralTxOutId]
  , rPoolUpdateIds        :: ![PoolUpdateId]
  , rPoolMetadataRefIds   :: ![PoolMetadataRefId]
  , rRedeemerIds          :: ![RedeemerId]
  , rGovActionProposalIds :: ![GovActionProposalId]
  , rParamProposalIds     :: ![ParamProposalId]
  , rCommitteeIds         :: ![CommitteeId]
  , rConstitutionIds      :: ![ConstitutionId]
  }

wrapInRefs :: AllocatedIdsRaw -> IO PreAllocatedIds
wrapInRefs r =
  PreAllocatedIds
    <$> newIORef (rTxIds r)
    <*> newIORef (rTxOutIds r)
    <*> newIORef (rCollateralTxOutIds r)
    <*> newIORef (rPoolUpdateIds r)
    <*> newIORef (rPoolMetadataRefIds r)
    <*> newIORef (rRedeemerIds r)
    <*> newIORef (rGovActionProposalIds r)
    <*> newIORef (rParamProposalIds r)
    <*> newIORef (rCommitteeIds r)
    <*> newIORef (rConstitutionIds r)

-- | Issue one bulk @nextval@ call for the table's sequence. A zero
-- count issues no statement. Otherwise
-- @SELECT nextval(seq) FROM generate_series(1, $1)@ returns N rows
-- in one statement, batched with the other tables.
allocFor
  :: TableDef
  -> Int                          -- ^ How many IDs to allocate (may be 0).
  -> (Int64 -> a)                 -- ^ ID constructor.
  -> Pipeline.Pipeline [a]
allocFor _  0 _    = pure []
allocFor td n ctor =
  Pipeline.statement (fromIntegral n) (bulkNextvalStmt td ctor)
