{-# LANGUAGE OverloadedStrings #-}

-- | Pre-allocate every assignable ID a block will need in a single
-- libpq pipeline round-trip.
--
-- Replaces the per-row @SELECT nextval(seq)@ call site by:
--
--   1. Walking the block once via 'IdCounts.countAssignableIds'.
--   2. Issuing one @SELECT nextval(seq) FROM generate_series(1, N)@
--      per non-zero sequence, batched as a single 'Hasql.Pipeline'.
--   3. Stashing the returned IDs in per-table 'IORef' queues that
--      the Follow 'IdResolver' pops from at zero round-trips.
--
-- Only FK-referenced tables need pre-allocation; leaf tables use
-- @GENERATED BY DEFAULT AS IDENTITY@ and let PostgreSQL allocate at
-- INSERT time.
module DbSync.Phase.Following.IdAllocator
  ( PreAllocatedIds (..)
  , allocateAllIds
  , popHead
  , unused
  ) where

import Cardano.Prelude

import Data.IORef (IORef, atomicModifyIORef', newIORef, readIORef)
import qualified Hasql.Connection as Conn
import qualified Hasql.Pipeline as Pipeline
import qualified Hasql.Session as Sess

import DbSync.Db.Run (useConn)
import DbSync.Db.Schema.Ids
  ( CollateralTxOutId (..)
  , PoolMetadataRefId (..)
  , PoolUpdateId (..)
  , TxId (..)
  , TxOutId (..)
  )
import DbSync.Db.Schema.Types (TableDef)
import DbSync.Db.Statement.IdAllocator (bulkNextvalStmt)
import DbSync.Db.Schema.UTxO (collateralTxOutTableDef, txOutTableDef)
import DbSync.Db.Schema.Core (txTableDef)
import DbSync.Db.Schema.Pool (poolMetadataRefTableDef, poolUpdateTableDef)
import DbSync.Phase.Following.IdCounts (IdCounts (..))

-- | Per-sequence FIFO of IDs allocated for the current block.
--
-- One 'IORef' per sequence so the resolver can pop without
-- contending across tables. Each queue is filled exactly once by
-- 'allocateAllIds' and drained exactly once by the extractor pass;
-- 'popHead' panics on empty so a miscounted block fails loudly.
data PreAllocatedIds = PreAllocatedIds
  { paiTxIds              :: !(IORef [TxId])
  , paiTxOutIds           :: !(IORef [TxOutId])
  , paiCollateralTxOutIds :: !(IORef [CollateralTxOutId])
  , paiPoolUpdateIds      :: !(IORef [PoolUpdateId])
  , paiPoolMetadataRefIds :: !(IORef [PoolMetadataRefId])
  }

-- | Pop the next ID from a per-sequence queue. Panics if the
-- extractor pass requests more IDs than 'allocateAllIds'
-- pre-fetched — that's a counting bug in 'IdCounts' and we want
-- the test suite to catch it loudly.
popHead :: Text -> IORef [a] -> IO a
popHead label ref =
  atomicModifyIORef' ref $ \case
    (x : xs) -> (xs, x)
    []       -> panic $
      "IdAllocator.popHead: queue exhausted for " <> label
        <> ". IdCounts undercount; investigate the count walker."

-- | Number of unconsumed IDs left in a queue. Tests use this to
-- assert the extractor consumed exactly what was pre-allocated.
unused :: IORef [a] -> IO Int
unused ref = length <$> readIORef ref

-- | Allocate every ID the block will need in one pipeline batch.
allocateAllIds :: Conn.Connection -> IdCounts -> IO PreAllocatedIds
allocateAllIds conn counts = do
  let pipeline =
        AllocatedIdsRaw
          <$> allocFor txTableDef              (icTxIds counts)              TxId
          <*> allocFor txOutTableDef           (icTxOutIds counts)           TxOutId
          <*> allocFor collateralTxOutTableDef (icCollateralTxOutIds counts) CollateralTxOutId
          <*> allocFor poolUpdateTableDef      (icPoolUpdateIds counts)      PoolUpdateId
          <*> allocFor poolMetadataRefTableDef (icPoolMetadataRefIds counts) PoolMetadataRefId

  raw <- useConn "Phase.Following.IdAllocator" conn (Sess.pipeline pipeline)
  wrapInRefs raw

-- | Intermediate record carrying the raw lists returned by the
-- pipeline. Converted into the 'IORef'-of-queue shape by
-- 'wrapInRefs' so the extractor can pop in-place.
data AllocatedIdsRaw = AllocatedIdsRaw
  { rTxIds              :: ![TxId]
  , rTxOutIds           :: ![TxOutId]
  , rCollateralTxOutIds :: ![CollateralTxOutId]
  , rPoolUpdateIds      :: ![PoolUpdateId]
  , rPoolMetadataRefIds :: ![PoolMetadataRefId]
  }

wrapInRefs :: AllocatedIdsRaw -> IO PreAllocatedIds
wrapInRefs r =
  PreAllocatedIds
    <$> newIORef (rTxIds r)
    <*> newIORef (rTxOutIds r)
    <*> newIORef (rCollateralTxOutIds r)
    <*> newIORef (rPoolUpdateIds r)
    <*> newIORef (rPoolMetadataRefIds r)

-- | Issue one bulk @nextval@ call for the given table's sequence.
--
-- Zero-count case is a no-op: no pipeline statement issued, an empty
-- list returned immediately via 'pure'.
--
-- Non-zero case: @SELECT nextval(seq) FROM generate_series(1, $1)@
-- returns N rows in one statement; the pipeline batches it with
-- the other tables' allocations. The SQL itself lives in
-- 'DbSync.Db.Statement.IdAllocator'.
allocFor
  :: TableDef
  -> Int                          -- ^ How many IDs to allocate (may be 0).
  -> (Int64 -> a)                 -- ^ ID constructor.
  -> Pipeline.Pipeline [a]
allocFor _  0 _    = pure []
allocFor td n ctor =
  Pipeline.statement (fromIntegral n) (bulkNextvalStmt td ctor)
