{-# LANGUAGE OverloadedStrings #-}

-- | @CREATE TABLE@ DDL generation from 'TableDef' definitions.
module DbSync.Db.Schema.Generate
  ( generateCreateTable
  , formatColumnDdl
  , pgTypeToSql
  ) where

import Cardano.Prelude

import Data.List (lookup)
import qualified Data.Text as T

import DbSync.Db.Schema.Types
  ( ColumnDef (..)
  , PgType (..)
  , TableDef (..)
  , TableMode (..)
  )
import DbSync.Db.Sql (quoteIdent)

-- | Emit the columns, then the primary key, then the checks, in that
-- stable order. Indexes and foreign keys come later, in
-- 'PreparingForVolatileTail'.
--
-- @
-- CREATE TABLE "dbsync_sync_state" (
--   "id" SMALLINT NOT NULL DEFAULT 1,
--   "block_id_counter" BIGINT NOT NULL DEFAULT 1,
--   PRIMARY KEY ("id"),
--   CHECK ("id" = 1)
-- );
-- @
generateCreateTable :: TableDef -> Text
generateCreateTable td =
  T.unlines $
    [ createLine ]
    ++ bodyLines
    ++ [ ");" ]
  where
    createLine :: Text
    createLine =
      let modeStr = case tdMode td of
            TableUnlogged -> "CREATE UNLOGGED TABLE"
            TableLogged   -> "CREATE TABLE"
      in modeStr <> " " <> quoteIdent (tdName td) <> " ("

    -- One comma-separated item per line; every line but the last gets
    -- a trailing comma.
    bodyLines :: [Text]
    bodyLines =
      let columnLines = map formatColumn (tdColumns td)
          pkLine = case tdPrimaryKey td of
            Nothing   -> []
            Just cols -> [ "PRIMARY KEY (" <> T.intercalate ", " (map quoteIdent cols) <> ")" ]
          checkLines = map (\expr -> "CHECK (" <> expr <> ")") (tdChecks td)
          allItems = columnLines ++ pkLine ++ checkLines
          total = length allItems
      in zipWith (\idx item -> "  " <> item <> commaFor total idx) [1..] allItems

    commaFor :: Int -> Int -> Text
    commaFor total idx
      | idx < total = ","
      | otherwise   = ""

    -- A generated column gets no NOT NULL and no DEFAULT: the expression
    -- replaces the default, and PostgreSQL infers nullability from it.
    -- An identity column uses the @BY DEFAULT@ variant, so an operator can
    -- override the value during a restore from dump.
    formatColumn :: ColumnDef -> Text
    formatColumn col =
      let typeSql = pgTypeToSql (cdType col)
          quoted  = quoteIdent (cdName col)
          name    = cdName col
      in if name `elem` tdIdentityColumns td
           then quoted <> " " <> typeSql <> " GENERATED BY DEFAULT AS IDENTITY"
           else case lookup name (tdGeneratedColumns td) of
                  Just expr ->
                    quoted <> " " <> typeSql <> " GENERATED ALWAYS AS (" <> expr <> ") STORED"
                  Nothing ->
                    let defaultClause = case lookup name (tdColumnDefaults td) of
                          Nothing   -> ""
                          Just expr -> " DEFAULT " <> expr
                    in formatColumnDdl col <> defaultClause

-- | A column's base DDL — @"name" TYPE@ with @NOT NULL@ when the
-- column is not nullable. 'generateCreateTable' layers column defaults,
-- identity, and generated-column clauses on top of this; an
-- @ALTER TABLE … ADD COLUMN@ reuses it as-is.
formatColumnDdl :: ColumnDef -> Text
formatColumnDdl col =
  quoteIdent (cdName col) <> " " <> pgTypeToSql (cdType col) <> nullability
  where
    nullability = if cdNullable col then "" else " NOT NULL"

pgTypeToSql :: PgType -> Text
pgTypeToSql = \case
  PgBigInt      -> "BIGINT"
  PgInteger     -> "INTEGER"
  PgSmallInt    -> "SMALLINT"
  PgText        -> "TEXT"
  PgBytea       -> "BYTEA"
  PgJsonb       -> "JSONB"
  PgBoolean     -> "BOOLEAN"
  PgNumeric     -> "NUMERIC"
  PgTimestamp   -> "TIMESTAMP WITHOUT TIME ZONE"
  PgTimestampTz -> "TIMESTAMP WITH TIME ZONE"
  PgTextArray   -> "TEXT[]"
