{-# LANGUAGE OverloadedStrings #-}

-- | Schema definition types that generate @CREATE TABLE@ DDL at runtime.
--
-- 'IngestChainHistory' creates the extractor tables UNLOGGED, with no
-- indexes and no constraints.
module DbSync.Db.Schema.Types
  ( -- * Types
    TableDef (..)
  , ColumnDef (..)
  , ParentRef (..)
  , PgType (..)
  , TableMode (..)
  , TableColumn (..)

    -- * Ownership-graph queries
  , childrenOf
  ) where

import Cardano.Prelude

-- ---------------------------------------------------------------------------
-- * Types
-- ---------------------------------------------------------------------------

data TableMode
  = TableLogged    -- ^ Normal table with WAL (for FollowingChainTip)
  | TableUnlogged  -- ^ UNLOGGED table (for IngestChainHistory — no WAL)
  deriving stock (Eq, Show)

-- | PostgreSQL column type.
--
-- A generated column has no constructor here: 'cdType' holds its SQL type
-- and 'tdGeneratedColumns' holds the expression.
data PgType
  = PgBigInt        -- ^ BIGINT (int8)
  | PgInteger       -- ^ INTEGER (int4)
  | PgSmallInt      -- ^ SMALLINT (int2)
  | PgText          -- ^ TEXT
  | PgBytea         -- ^ BYTEA
  | PgJsonb         -- ^ JSONB
  | PgBoolean       -- ^ BOOLEAN
  | PgNumeric       -- ^ NUMERIC
  | PgTimestamp     -- ^ TIMESTAMP WITHOUT TIME ZONE
  | PgTimestampTz   -- ^ TIMESTAMP WITH TIME ZONE
  | PgTextArray     -- ^ TEXT[]
  deriving stock (Eq, Show)

data ColumnDef = ColumnDef
  { cdName     :: !Text
  , cdType     :: !PgType
  , cdNullable :: !Bool
  }
  deriving stock (Eq, Show)

-- | An ownership edge: rows of this table belong to a row of
-- 'prParentTable' and must die with it. Drives the resume trim, the
-- rollback cascade, and the @FOREIGN KEY@ constraints created in
-- 'PreparingForVolatileTail'.
--
-- Only ownership is declared. Transactions share a reference to a
-- deduplicated row — @tx_out.inline_datum_id@, @tx_in.redeemer_id@,
-- @ma_tx_out.ident@ — so no rollback cascades it and no constraint
-- covers it.
data ParentRef = ParentRef
  { prColumn       :: !Text  -- ^ This table's referencing column.
  , prParentTable  :: !Text  -- ^ Owning table.
  , prParentColumn :: !Text  -- ^ Parent table's column (usually @"id"@).
  }
  deriving stock (Eq, Show)

-- | Definition of a database table, consumed by 'DbSync.Schema.Generate'.
--
-- The list- and 'Maybe'-shaped fields are empty for the extractor data
-- tables. They carry the constraints of the few LOGGED-from-day-one
-- tables, plus per-table metadata that 'PreparingForVolatileTail' and
-- DDL emission read later.
data TableDef = TableDef
  { tdName              :: !Text
  , tdColumns           :: ![ColumnDef]
  , tdMode              :: !TableMode
  , tdPrimaryKey        :: !(Maybe [Text])
      -- ^ 'Just cols' emits @PRIMARY KEY (col1, …)@ in the DDL and
      -- matches the index that 'PreparingForVolatileTail' builds.
      -- 'Nothing' is the default for extractor data tables: the DDL
      -- has no PK clause, because UNLOGGED COPY must pay no index
      -- cost, and the post-load index builder reads it as @["id"]@.
  , tdChecks            :: ![Text]
      -- ^ Table-level constraint expressions, each emitted verbatim
      -- as @CHECK (expr)@.
  , tdColumnDefaults    :: ![(Text, Text)]
      -- ^ Per-column @DEFAULT@ expressions, keyed by column name and
      -- emitted verbatim after the type. An absent column gets no
      -- default clause.
  , tdUniqueConstraints :: ![NonEmpty Text]
      -- ^ Table-level @UNIQUE (col1, …)@ constraints. The DDL omits
      -- them; 'PreparingForVolatileTail' indexing adds them.
  , tdGeneratedColumns  :: ![(Text, Text)]
      -- ^ Per-column @GENERATED ALWAYS AS (expr) STORED@ definitions,
      -- keyed by column name. 'DbSync.Db.Loader.Connection.beginStream'
      -- drops these columns from the COPY column list, so PostgreSQL
      -- computes them on insert.
  , tdIdentityColumns   :: ![Text]
      -- ^ Columns emitted as @BIGINT GENERATED BY DEFAULT AS IDENTITY@,
      -- so PostgreSQL allocates the values. Used for leaf-table @id@
      -- columns that no other table references, which keeps the
      -- 'IdCounter' out of the resolver. The COPY column list drops
      -- these columns too.
  , tdParentRefs        :: ![ParentRef]
      -- ^ Rows this table's rows belong to. Drives the resume trim and
      -- the rollback cascade; empty only when no column points at
      -- @block@, @tx@, @tx_out@ or @pool_update@.
  }
  deriving stock (Eq, Show)

-- | A column reference that carries its owning 'TableDef', built from the
-- per-table column records (e.g. @poolHashCols.phcHashRaw@) and consumed
-- by 'DbSync.Db.Sql.Refs'. The pairing turns a mismatched reference into
-- a type error instead of a runtime panic.
data TableColumn = TableColumn
  { tcTable :: !TableDef
  , tcName  :: !Text
  }
  deriving stock (Eq, Show)

-- ---------------------------------------------------------------------------
-- * Ownership-graph queries
-- ---------------------------------------------------------------------------

-- | Tables declaring an ownership edge to @parentTable@, each paired
-- with its referencing column.
childrenOf :: [TableDef] -> Text -> [(Text, Text)]
childrenOf tables parentTable =
  [ (tdName td, prColumn pr)
  | td <- tables
  , pr <- tdParentRefs td
  , prParentTable pr == parentTable
  ]
