{-# LANGUAGE OverloadedStrings #-}

-- | Hasql 'Statement' bindings for the @tx_in@ table.
--
-- Used during 'FollowingChainTip' for per-input INSERTs. The
-- 'IngestChainHistory' phase writes via COPY instead. PostgreSQL
-- assigns the @id@ via the table's @GENERATED BY DEFAULT AS IDENTITY@
-- column, so the statement supplies the data columns only.
--
-- @tx_out_id@ is left NULL during ingest; it is resolved post-load by
-- a SQL join in 'PreparingForVolatileTail'. The same convention applies
-- here in FollowingChainTip — the writer never sets it.
module DbSync.Db.Statement.TxIn
  ( insertTxInRowStmt
  ) where

import Cardano.Prelude

import qualified Data.Text as T
import qualified Hasql.Decoders as D
import qualified Hasql.Statement as Stmt

import DbSync.Db.Schema.Types (TableDef (..))
import DbSync.Db.Schema.UTxO (TxIn, txInEncoder, txInTableDef)

table :: Text
table = tdName txInTableDef

insertTxInRowStmt :: Stmt.Statement TxIn ()
insertTxInRowStmt =
  Stmt.preparable sql txInEncoder D.noResult
  where
    sql = T.concat
      [ "INSERT INTO ", table
      , " (tx_in_id, tx_out_id, tx_out_index, tx_out_hash, redeemer_id)"
      , " VALUES ($1, $2, $3, $4, $5)"
      ]
