-- dbsync schema baseline (schema version 1).
-- Generated by gen-migration; do not edit by hand.
--
-- Frozen record of the v1 logical schema: this file plus the incremental
-- vN migration files rebuild the schema from empty. A fresh production
-- database is built by initSchema, not by this file.

CREATE TABLE "dbsync_sync_state" (
  "id" SMALLINT NOT NULL DEFAULT 1,
  "last_committed_slot" BIGINT,
  "last_committed_block_no" BIGINT,
  "last_committed_block_hash" BYTEA,
  "last_snapshot_slot" BIGINT,
  "block_id_counter" BIGINT NOT NULL DEFAULT 1,
  "tx_id_counter" BIGINT NOT NULL DEFAULT 1,
  "tx_out_id_counter" BIGINT NOT NULL DEFAULT 1,
  "slot_leader_id_counter" BIGINT NOT NULL DEFAULT 1,
  "address_id_counter" BIGINT NOT NULL DEFAULT 1,
  "stake_address_id_counter" BIGINT NOT NULL DEFAULT 1,
  "pool_hash_id_counter" BIGINT NOT NULL DEFAULT 1,
  "multi_asset_id_counter" BIGINT NOT NULL DEFAULT 1,
  "script_id_counter" BIGINT NOT NULL DEFAULT 1,
  "pool_update_id_counter" BIGINT NOT NULL DEFAULT 1,
  "pool_metadata_ref_id_counter" BIGINT NOT NULL DEFAULT 1,
  "cost_model_id_counter" BIGINT NOT NULL DEFAULT 1,
  "redeemer_id_counter" BIGINT NOT NULL DEFAULT 1,
  "collateral_tx_out_id_counter" BIGINT NOT NULL DEFAULT 1,
  "epoch_sync_stats_id_counter" BIGINT NOT NULL DEFAULT 1,
  "gov_action_proposal_id_counter" BIGINT NOT NULL DEFAULT 1,
  "param_proposal_id_counter" BIGINT NOT NULL DEFAULT 1,
  "committee_id_counter" BIGINT NOT NULL DEFAULT 1,
  "constitution_id_counter" BIGINT NOT NULL DEFAULT 1,
  "event_info_id_counter" BIGINT NOT NULL DEFAULT 1,
  "schema_version_applied" INTEGER NOT NULL,
  "ledger_enabled" BOOLEAN NOT NULL,
  "sync_complete" BOOLEAN NOT NULL DEFAULT false,
  "pending_rollback_slot" BIGINT,
  "schema_fingerprint" TEXT NOT NULL,
  "extractors" TEXT[] NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CHECK ("id" = 1)
);

CREATE TABLE "epoch_param_pending" (
  "epoch_no" BIGINT NOT NULL,
  "stake_key_deposit" NUMERIC NOT NULL,
  "pool_deposit" NUMERIC NOT NULL,
  PRIMARY KEY ("epoch_no")
);

CREATE UNLOGGED TABLE "block" (
  "id" BIGINT NOT NULL,
  "hash" BYTEA NOT NULL,
  "epoch_no" BIGINT,
  "slot_no" BIGINT,
  "epoch_slot_no" BIGINT,
  "block_no" BIGINT,
  "previous_id" BIGINT,
  "slot_leader_id" BIGINT NOT NULL,
  "size" BIGINT NOT NULL,
  "time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "tx_count" BIGINT NOT NULL,
  "proto_major" SMALLINT NOT NULL,
  "proto_minor" SMALLINT NOT NULL,
  "vrf_key" TEXT,
  "op_cert" BYTEA,
  "op_cert_counter" BIGINT
);

CREATE UNLOGGED TABLE "tx" (
  "id" BIGINT NOT NULL,
  "hash" BYTEA NOT NULL,
  "block_id" BIGINT NOT NULL,
  "block_index" BIGINT NOT NULL,
  "out_sum" NUMERIC NOT NULL,
  "fee" NUMERIC NOT NULL,
  "deposit" BIGINT,
  "size" BIGINT NOT NULL,
  "invalid_before" NUMERIC,
  "invalid_hereafter" NUMERIC,
  "valid_contract" BOOLEAN NOT NULL,
  "script_size" BIGINT NOT NULL,
  "treasury_donation" NUMERIC NOT NULL
);

CREATE UNLOGGED TABLE "slot_leader" (
  "id" BIGINT NOT NULL,
  "hash" BYTEA NOT NULL,
  "pool_hash_id" BIGINT,
  "description" TEXT NOT NULL
);

CREATE UNLOGGED TABLE "stake_address" (
  "id" BIGINT NOT NULL,
  "hash_raw" BYTEA NOT NULL,
  "view" TEXT NOT NULL,
  "script_hash" BYTEA
);

CREATE UNLOGGED TABLE "pool_hash" (
  "id" BIGINT NOT NULL,
  "hash_raw" BYTEA NOT NULL,
  "view" TEXT NOT NULL
);

CREATE UNLOGGED TABLE "address" (
  "id" BIGINT NOT NULL,
  "address" TEXT NOT NULL,
  "raw" BYTEA NOT NULL,
  "has_script" BOOLEAN NOT NULL,
  "payment_cred" BYTEA,
  "stake_address_id" BIGINT,
  "raw_hash" BYTEA GENERATED ALWAYS AS (decode(md5(raw), 'hex')) STORED
);

CREATE UNLOGGED TABLE "tx_out" (
  "id" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "address_id" BIGINT,
  "stake_address_id" BIGINT,
  "value" NUMERIC NOT NULL,
  "data_hash" BYTEA,
  "inline_datum_id" BIGINT,
  "reference_script_id" BIGINT,
  "consumed_by_tx_id" BIGINT
);

CREATE UNLOGGED TABLE "tx_in" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tx_in_id" BIGINT NOT NULL,
  "tx_out_id" BIGINT,
  "tx_out_index" BIGINT NOT NULL,
  "tx_out_hash" BYTEA NOT NULL,
  "redeemer_id" BIGINT
);

CREATE UNLOGGED TABLE "collateral_tx_in" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tx_in_id" BIGINT NOT NULL,
  "tx_out_id" BIGINT,
  "tx_out_index" BIGINT NOT NULL,
  "tx_out_hash" BYTEA NOT NULL
);

CREATE UNLOGGED TABLE "collateral_tx_out" (
  "id" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "address_id" BIGINT,
  "stake_address_id" BIGINT,
  "value" NUMERIC NOT NULL,
  "data_hash" BYTEA,
  "multi_assets_descr" TEXT NOT NULL,
  "inline_datum_id" BIGINT,
  "reference_script_id" BIGINT
);

CREATE UNLOGGED TABLE "reference_tx_in" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tx_in_id" BIGINT NOT NULL,
  "tx_out_id" BIGINT,
  "tx_out_index" BIGINT NOT NULL,
  "tx_out_hash" BYTEA NOT NULL
);

CREATE UNLOGGED TABLE "multi_asset" (
  "id" BIGINT NOT NULL,
  "policy" BYTEA NOT NULL,
  "name" BYTEA NOT NULL,
  "fingerprint" TEXT NOT NULL
);

CREATE UNLOGGED TABLE "ma_tx_mint" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "quantity" NUMERIC NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "ident" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "ma_tx_out" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "quantity" NUMERIC NOT NULL,
  "tx_out_id" BIGINT NOT NULL,
  "ident" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "tx_metadata" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "key" NUMERIC NOT NULL,
  "json" JSONB,
  "bytes" BYTEA NOT NULL,
  "tx_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "stake_registration" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "epoch_no" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "deposit" NUMERIC
);

CREATE UNLOGGED TABLE "stake_deregistration" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "epoch_no" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "redeemer_id" BIGINT
);

CREATE UNLOGGED TABLE "delegation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "pool_hash_id" BIGINT NOT NULL,
  "active_epoch_no" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "slot_no" BIGINT NOT NULL,
  "redeemer_id" BIGINT
);

CREATE UNLOGGED TABLE "withdrawal" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "redeemer_id" BIGINT
);

CREATE UNLOGGED TABLE "pot_transfer" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "cert_index" BIGINT NOT NULL,
  "treasury" NUMERIC NOT NULL,
  "reserves" NUMERIC NOT NULL,
  "tx_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "reserve" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "tx_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "treasury" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "tx_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "reward" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "type" TEXT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "spendable_epoch" BIGINT NOT NULL,
  "pool_id" BIGINT NOT NULL,
  "earned_epoch" BIGINT GENERATED ALWAYS AS ((CASE WHEN (type='refund') then spendable_epoch else (CASE WHEN spendable_epoch >= 2 then spendable_epoch-2 else 0 end) end)) STORED
);

CREATE UNLOGGED TABLE "pot_reward" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "type" TEXT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "spendable_epoch" BIGINT NOT NULL,
  "earned_epoch" BIGINT GENERATED ALWAYS AS ((CASE WHEN spendable_epoch >= 1 then spendable_epoch-1 else 0 end)) STORED
);

CREATE UNLOGGED TABLE "epoch_stake" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "pool_id" BIGINT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "epoch_no" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "epoch_stake_progress" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "epoch_no" BIGINT NOT NULL,
  "completed" BOOLEAN NOT NULL
);

CREATE UNLOGGED TABLE "pool_update" (
  "id" BIGINT NOT NULL,
  "hash_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "vrf_key_hash" BYTEA NOT NULL,
  "pledge" NUMERIC NOT NULL,
  "active_epoch_no" BIGINT NOT NULL,
  "meta_id" BIGINT,
  "margin" TEXT NOT NULL,
  "fixed_cost" NUMERIC NOT NULL,
  "registered_tx_id" BIGINT NOT NULL,
  "reward_addr_id" BIGINT NOT NULL,
  "deposit" NUMERIC
);

CREATE UNLOGGED TABLE "pool_metadata_ref" (
  "id" BIGINT NOT NULL,
  "pool_id" BIGINT NOT NULL,
  "url" TEXT NOT NULL,
  "hash" BYTEA NOT NULL,
  "registered_tx_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "pool_owner" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "pool_update_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "pool_retire" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "hash_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "announced_tx_id" BIGINT NOT NULL,
  "retiring_epoch" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "pool_relay" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "update_id" BIGINT NOT NULL,
  "ipv4" TEXT,
  "ipv6" TEXT,
  "dns_name" TEXT,
  "dns_srv_name" TEXT,
  "port" BIGINT
);

CREATE UNLOGGED TABLE "datum" (
  "id" BIGINT NOT NULL,
  "hash" BYTEA NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "value" JSONB,
  "bytes" BYTEA NOT NULL
);

CREATE UNLOGGED TABLE "script" (
  "id" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "hash" BYTEA NOT NULL,
  "type" TEXT NOT NULL,
  "json" JSONB,
  "bytes" BYTEA,
  "serialised_size" BIGINT
);

CREATE UNLOGGED TABLE "redeemer" (
  "id" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "unit_mem" BIGINT NOT NULL,
  "unit_steps" BIGINT NOT NULL,
  "fee" NUMERIC,
  "purpose" TEXT NOT NULL,
  "index" BIGINT NOT NULL,
  "script_hash" BYTEA,
  "redeemer_data_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "redeemer_data" (
  "id" BIGINT NOT NULL,
  "hash" BYTEA NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "value" JSONB,
  "bytes" BYTEA NOT NULL
);

CREATE UNLOGGED TABLE "extra_key_witness" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "hash" BYTEA NOT NULL,
  "tx_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "drep_hash" (
  "id" BIGINT NOT NULL,
  "raw" BYTEA,
  "view" TEXT NOT NULL,
  "has_script" BOOLEAN NOT NULL
);

CREATE UNLOGGED TABLE "drep_registration" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tx_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "deposit" BIGINT,
  "drep_hash_id" BIGINT NOT NULL,
  "voting_anchor_id" BIGINT
);

CREATE UNLOGGED TABLE "drep_distr" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "hash_id" BIGINT NOT NULL,
  "amount" BIGINT NOT NULL,
  "epoch_no" BIGINT NOT NULL,
  "active_until" BIGINT
);

CREATE UNLOGGED TABLE "delegation_vote" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "addr_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "drep_hash_id" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "redeemer_id" BIGINT
);

CREATE UNLOGGED TABLE "gov_action_proposal" (
  "id" BIGINT NOT NULL,
  "tx_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "prev_gov_action_proposal" BIGINT,
  "deposit" NUMERIC NOT NULL,
  "return_address" BIGINT NOT NULL,
  "expiration" BIGINT,
  "voting_anchor_id" BIGINT,
  "type" TEXT NOT NULL,
  "description" JSONB NOT NULL,
  "param_proposal" BIGINT,
  "ratified_epoch" BIGINT,
  "enacted_epoch" BIGINT,
  "dropped_epoch" BIGINT,
  "expired_epoch" BIGINT
);

CREATE UNLOGGED TABLE "voting_procedure" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tx_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "gov_action_proposal_id" BIGINT NOT NULL,
  "voter_role" TEXT NOT NULL,
  "drep_voter" BIGINT,
  "pool_voter" BIGINT,
  "vote" TEXT NOT NULL,
  "voting_anchor_id" BIGINT,
  "committee_voter" BIGINT,
  "invalid" BIGINT
);

CREATE UNLOGGED TABLE "voting_anchor" (
  "id" BIGINT NOT NULL,
  "url" TEXT NOT NULL,
  "data_hash" BYTEA NOT NULL,
  "type" TEXT NOT NULL,
  "block_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "constitution" (
  "id" BIGINT NOT NULL,
  "gov_action_proposal_id" BIGINT,
  "voting_anchor_id" BIGINT NOT NULL,
  "script_hash" BYTEA
);

CREATE UNLOGGED TABLE "committee" (
  "id" BIGINT NOT NULL,
  "gov_action_proposal_id" BIGINT,
  "quorum_numerator" BIGINT NOT NULL,
  "quorum_denominator" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "committee_hash" (
  "id" BIGINT NOT NULL,
  "raw" BYTEA NOT NULL,
  "has_script" BOOLEAN NOT NULL
);

CREATE UNLOGGED TABLE "committee_member" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "committee_id" BIGINT NOT NULL,
  "committee_hash_id" BIGINT NOT NULL,
  "expiration_epoch" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "committee_registration" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tx_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "cold_key_id" BIGINT NOT NULL,
  "hot_key_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "committee_de_registration" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tx_id" BIGINT NOT NULL,
  "cert_index" BIGINT NOT NULL,
  "voting_anchor_id" BIGINT,
  "cold_key_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "param_proposal" (
  "id" BIGINT NOT NULL,
  "epoch_no" BIGINT,
  "key" BYTEA,
  "min_fee_a" NUMERIC,
  "min_fee_b" NUMERIC,
  "max_block_size" NUMERIC,
  "max_tx_size" NUMERIC,
  "max_bh_size" NUMERIC,
  "key_deposit" NUMERIC,
  "pool_deposit" NUMERIC,
  "max_epoch" NUMERIC,
  "optimal_pool_count" NUMERIC,
  "influence" TEXT,
  "monetary_expand_rate" TEXT,
  "treasury_growth_rate" TEXT,
  "decentralisation" TEXT,
  "entropy" BYTEA,
  "protocol_major" SMALLINT,
  "protocol_minor" SMALLINT,
  "min_utxo_value" NUMERIC,
  "min_pool_cost" NUMERIC,
  "cost_model_id" BIGINT,
  "price_mem" TEXT,
  "price_step" TEXT,
  "max_tx_ex_mem" NUMERIC,
  "max_tx_ex_steps" NUMERIC,
  "max_block_ex_mem" NUMERIC,
  "max_block_ex_steps" NUMERIC,
  "max_val_size" NUMERIC,
  "collateral_percent" SMALLINT,
  "max_collateral_inputs" SMALLINT,
  "registered_tx_id" BIGINT NOT NULL,
  "coins_per_utxo_size" NUMERIC,
  "pvt_motion_no_confidence" TEXT,
  "pvt_committee_normal" TEXT,
  "pvt_committee_no_confidence" TEXT,
  "pvt_hard_fork_initiation" TEXT,
  "pvtpp_security_group" TEXT,
  "dvt_motion_no_confidence" TEXT,
  "dvt_committee_normal" TEXT,
  "dvt_committee_no_confidence" TEXT,
  "dvt_update_to_constitution" TEXT,
  "dvt_hard_fork_initiation" TEXT,
  "dvt_pp_network_group" TEXT,
  "dvt_pp_economic_group" TEXT,
  "dvt_pp_technical_group" TEXT,
  "dvt_pp_gov_group" TEXT,
  "dvt_treasury_withdrawal" TEXT,
  "committee_min_size" NUMERIC,
  "committee_max_term_length" NUMERIC,
  "gov_action_lifetime" NUMERIC,
  "gov_action_deposit" NUMERIC,
  "drep_deposit" NUMERIC,
  "drep_activity" NUMERIC,
  "min_fee_ref_script_cost_per_byte" TEXT
);

CREATE UNLOGGED TABLE "treasury_withdrawal" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "gov_action_proposal_id" BIGINT NOT NULL,
  "stake_address_id" BIGINT NOT NULL,
  "amount" NUMERIC NOT NULL
);

CREATE UNLOGGED TABLE "event_info" (
  "id" BIGINT NOT NULL,
  "tx_id" BIGINT,
  "epoch" BIGINT NOT NULL,
  "type" TEXT NOT NULL,
  "explanation" TEXT
);

CREATE UNLOGGED TABLE "tx_cbor" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tx_id" BIGINT NOT NULL,
  "bytes" BYTEA NOT NULL
);

CREATE UNLOGGED TABLE "epoch_sync_stats" (
  "id" BIGINT NOT NULL,
  "epoch_no" BIGINT NOT NULL,
  "blocks_processed" BIGINT NOT NULL,
  "blocks_per_sec" NUMERIC NOT NULL,
  "elapsed_sec" NUMERIC NOT NULL,
  "synced_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "phase" TEXT NOT NULL
);

CREATE UNLOGGED TABLE "ada_pots" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "slot_no" BIGINT NOT NULL,
  "epoch_no" BIGINT NOT NULL,
  "treasury" NUMERIC NOT NULL,
  "reserves" NUMERIC NOT NULL,
  "rewards" NUMERIC NOT NULL,
  "utxo" NUMERIC NOT NULL,
  "deposits_stake" NUMERIC NOT NULL,
  "fees" NUMERIC NOT NULL,
  "block_id" BIGINT NOT NULL,
  "deposits_drep" NUMERIC NOT NULL,
  "deposits_proposal" NUMERIC NOT NULL
);

CREATE UNLOGGED TABLE "epoch_param" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "epoch_no" BIGINT NOT NULL,
  "min_fee_a" BIGINT NOT NULL,
  "min_fee_b" BIGINT NOT NULL,
  "max_block_size" BIGINT NOT NULL,
  "max_tx_size" BIGINT NOT NULL,
  "max_bh_size" BIGINT NOT NULL,
  "key_deposit" NUMERIC NOT NULL,
  "pool_deposit" NUMERIC NOT NULL,
  "max_epoch" BIGINT NOT NULL,
  "optimal_pool_count" BIGINT NOT NULL,
  "influence" TEXT NOT NULL,
  "monetary_expand_rate" TEXT NOT NULL,
  "treasury_growth_rate" TEXT NOT NULL,
  "decentralisation" TEXT NOT NULL,
  "protocol_major" SMALLINT NOT NULL,
  "protocol_minor" SMALLINT NOT NULL,
  "min_utxo_value" NUMERIC NOT NULL,
  "min_pool_cost" NUMERIC NOT NULL,
  "nonce" BYTEA,
  "cost_model_id" BIGINT,
  "price_mem" TEXT,
  "price_step" TEXT,
  "max_tx_ex_mem" NUMERIC,
  "max_tx_ex_steps" NUMERIC,
  "max_block_ex_mem" NUMERIC,
  "max_block_ex_steps" NUMERIC,
  "max_val_size" NUMERIC,
  "collateral_percent" SMALLINT,
  "max_collateral_inputs" SMALLINT,
  "block_id" BIGINT NOT NULL,
  "extra_entropy" BYTEA,
  "coins_per_utxo_size" NUMERIC,
  "pvt_motion_no_confidence" TEXT,
  "pvt_committee_normal" TEXT,
  "pvt_committee_no_confidence" TEXT,
  "pvt_hard_fork_initiation" TEXT,
  "dvt_motion_no_confidence" TEXT,
  "dvt_committee_normal" TEXT,
  "dvt_committee_no_confidence" TEXT,
  "dvt_update_to_constitution" TEXT,
  "dvt_hard_fork_initiation" TEXT,
  "dvt_pp_network_group" TEXT,
  "dvt_pp_economic_group" TEXT,
  "dvt_pp_technical_group" TEXT,
  "dvt_pp_gov_group" TEXT,
  "dvt_treasury_withdrawal" TEXT,
  "committee_min_size" NUMERIC,
  "committee_max_term_length" NUMERIC,
  "gov_action_lifetime" NUMERIC,
  "gov_action_deposit" NUMERIC,
  "drep_deposit" NUMERIC,
  "drep_activity" NUMERIC,
  "pvtpp_security_group" TEXT,
  "min_fee_ref_script_cost_per_byte" TEXT
);

CREATE UNLOGGED TABLE "epoch_state" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "committee_id" BIGINT,
  "no_confidence_id" BIGINT,
  "constitution_id" BIGINT,
  "epoch_no" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "cost_model" (
  "id" BIGINT NOT NULL,
  "costs" JSONB NOT NULL,
  "hash" BYTEA NOT NULL
);

CREATE UNLOGGED TABLE "pool_stat" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "pool_hash_id" BIGINT NOT NULL,
  "epoch_no" BIGINT NOT NULL,
  "number_of_blocks" NUMERIC NOT NULL,
  "number_of_delegators" NUMERIC NOT NULL,
  "stake" NUMERIC NOT NULL,
  "voting_power" NUMERIC
);

CREATE TABLE "epoch_finalized" (
  "id" BIGINT NOT NULL,
  "out_sum" NUMERIC NOT NULL,
  "fees" NUMERIC NOT NULL,
  "tx_count" BIGINT NOT NULL,
  "blk_count" BIGINT NOT NULL,
  "no" BIGINT NOT NULL,
  "start_time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "end_time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNLOGGED TABLE "off_chain_pool_data" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "pool_id" BIGINT NOT NULL,
  "ticker_name" TEXT NOT NULL,
  "hash" BYTEA NOT NULL,
  "json" JSONB NOT NULL,
  "bytes" BYTEA NOT NULL,
  "pmr_id" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "off_chain_pool_fetch_error" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "pool_id" BIGINT NOT NULL,
  "fetch_time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "pmr_id" BIGINT NOT NULL,
  "fetch_error" TEXT NOT NULL,
  "retry_count" BIGINT NOT NULL
);

CREATE UNLOGGED TABLE "delisted_pool" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "hash_raw" BYTEA NOT NULL
);

CREATE UNLOGGED TABLE "reserved_pool_ticker" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL,
  "pool_hash" BYTEA NOT NULL
);

CREATE UNLOGGED TABLE "off_chain_vote_data" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "voting_anchor_id" BIGINT NOT NULL,
  "hash" BYTEA NOT NULL,
  "json" JSONB NOT NULL,
  "bytes" BYTEA NOT NULL,
  "warning" TEXT,
  "language" TEXT NOT NULL,
  "comment" TEXT,
  "is_valid" BOOLEAN
);

CREATE UNLOGGED TABLE "off_chain_vote_gov_action_data" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "off_chain_vote_data_id" BIGINT NOT NULL,
  "title" TEXT NOT NULL,
  "abstract" TEXT NOT NULL,
  "motivation" TEXT NOT NULL,
  "rationale" TEXT NOT NULL
);

CREATE UNLOGGED TABLE "off_chain_vote_drep_data" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "off_chain_vote_data_id" BIGINT NOT NULL,
  "payment_address" TEXT,
  "given_name" TEXT NOT NULL,
  "objectives" TEXT,
  "motivations" TEXT,
  "qualifications" TEXT,
  "image_url" TEXT,
  "image_hash" TEXT
);

CREATE UNLOGGED TABLE "off_chain_vote_author" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "off_chain_vote_data_id" BIGINT NOT NULL,
  "name" TEXT,
  "witness_algorithm" TEXT NOT NULL,
  "public_key" TEXT NOT NULL,
  "signature" TEXT NOT NULL,
  "warning" TEXT
);

CREATE UNLOGGED TABLE "off_chain_vote_reference" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "off_chain_vote_data_id" BIGINT NOT NULL,
  "label" TEXT NOT NULL,
  "uri" TEXT NOT NULL,
  "hash_digest" TEXT,
  "hash_algorithm" TEXT
);

CREATE UNLOGGED TABLE "off_chain_vote_external_update" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "off_chain_vote_data_id" BIGINT NOT NULL,
  "title" TEXT NOT NULL,
  "uri" TEXT NOT NULL
);

CREATE UNLOGGED TABLE "off_chain_vote_fetch_error" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "voting_anchor_id" BIGINT NOT NULL,
  "fetch_error" TEXT NOT NULL,
  "fetch_time" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "retry_count" BIGINT NOT NULL
);


CREATE VIEW epoch_current AS
  SELECT
    (b.epoch_no::bigint + 1)                AS id,
    COALESCE(SUM(tx.out_sum), 0)::numeric            AS out_sum,
    COALESCE(SUM(tx.fee), 0)                         AS fees,
    COUNT(tx.id)::bigint                             AS tx_count,
    COUNT(DISTINCT b.id)::bigint        AS blk_count,
    b.epoch_no::bigint                      AS no,
    MIN(b.time)                           AS start_time,
    MAX(b.time)                           AS end_time
  FROM block b
  LEFT JOIN tx ON tx.block_id = b.id
  WHERE b.epoch_no IS NOT NULL
    AND b.epoch_no > COALESCE((SELECT MAX(no) FROM epoch_finalized), -1)
  GROUP BY b.epoch_no;

CREATE VIEW epoch AS
  SELECT id, out_sum, fees, tx_count, blk_count, no, start_time, end_time
    FROM epoch_finalized
  UNION ALL
  SELECT id, out_sum, fees, tx_count, blk_count, no, start_time, end_time
    FROM epoch_current;
