{-# LANGUAGE OverloadedStrings #-}

-- | Unit tests for 'rebuildTableScript'.
--
-- The override list is keyed by column name while the emitted SELECT
-- is ordered by 'tdColumns', so a mapping bug silently writes the
-- right value into the wrong column. These assertions pin the
-- positional contract; the e2e specs cover the values themselves.
module DbSync.Db.Statement.RebuildSpec (spec) where

import Cardano.Prelude

import qualified Data.Text as T

import Test.Hspec (Spec, describe, it, shouldBe, shouldNotSatisfy, shouldSatisfy)

import DbSync.Db.Schema.Types
  ( ColumnDef (..)
  , PgType (..)
  , TableDef (..)
  , TableMode (..)
  )
import DbSync.Db.Statement.Common (rebuildTableScript)

-- ---------------------------------------------------------------------------
-- Fixtures
-- ---------------------------------------------------------------------------

-- | @middle@ is nullable so the NOT NULL re-attachment has something
-- to skip, and sits between two passthrough columns so a
-- misplaced override shows up as a reordering.
target :: TableDef
target = TableDef
  { tdName    = "widget"
  , tdColumns =
      [ ColumnDef "id"     PgBigInt False
      , ColumnDef "before" PgBigInt False
      , ColumnDef "middle" PgBigInt True
      , ColumnDef "after"  PgBytea  False
      ]
  , tdMode              = TableUnlogged
  , tdPrimaryKey        = Nothing
  , tdChecks            = []
  , tdColumnDefaults    = []
  , tdUniqueConstraints = []
  , tdGeneratedColumns  = []
  , tdIdentityColumns   = []
  , tdParentRefs        = []
  }

rebuild :: [(Text, Text)] -> Text
rebuild overrides = rebuildTableScript target overrides "\"widget\" src"

lineStartingWith :: Text -> Text -> Maybe Text
lineStartingWith prefix script =
  find (T.isPrefixOf prefix) (T.lines script)

-- ---------------------------------------------------------------------------
-- Spec
-- ---------------------------------------------------------------------------

spec :: Spec
spec = describe "rebuildTableScript" $ do
  it "passes every column through from src when nothing is overridden" $
    lineStartingWith "SELECT" (rebuild [])
      `shouldBe` Just "SELECT src.\"id\", src.\"before\", src.\"middle\", src.\"after\""

  it "substitutes the override in the overridden column's own position" $
    lineStartingWith "SELECT" (rebuild [("middle", "42")])
      `shouldBe`
        Just "SELECT src.\"id\", src.\"before\", 42 AS \"middle\", src.\"after\""

  it "leaves a column absent from the override list untouched" $
    rebuild [("middle", "42")] `shouldNotSatisfy` T.isInfixOf "42 AS \"after\""

  it "builds the new table UNLOGGED, then swaps it in under the real name" $ do
    let script = rebuild []
    T.lines script `shouldSatisfy` \ls ->
      "CREATE UNLOGGED TABLE \"widget_new\" AS" `elem` ls
        && "DROP TABLE \"widget\";" `elem` ls
        && "ALTER TABLE \"widget_new\" RENAME TO \"widget\";" `elem` ls

  it "re-attaches NOT NULL for the non-nullable columns only" $
    lineStartingWith "ALTER TABLE \"widget\" ALTER" (rebuild [])
      `shouldBe`
        Just "ALTER TABLE \"widget\" ALTER COLUMN \"id\" SET NOT NULL,\
             \ ALTER COLUMN \"before\" SET NOT NULL,\
             \ ALTER COLUMN \"after\" SET NOT NULL;"

  -- The flip wires the id DEFAULT for counter-managed tables, so a
  -- rebuild that emitted one would collide with it.
  it "emits no id DEFAULT when the table declares no identity column" $
    rebuild [] `shouldNotSatisfy` T.isInfixOf "SET DEFAULT"

  it "re-attaches identity when the table declares one" $
    rebuildTableScript
      target { tdIdentityColumns = ["id"] } [] "\"widget\" src"
      `shouldSatisfy` T.isInfixOf
        "ALTER TABLE \"widget\" ALTER COLUMN \"id\"\
        \ ADD GENERATED BY DEFAULT AS IDENTITY;"
